let work = [
  {
    id: 1,
    start: "02/08/2019",
    end: "12/12/2019",
    title: "Teacher",
    company: "Cambridge College, Bolivia",
    country: "Bolivia",
    state: "Santa Cruz",
    description: ,
  }, 
  {
    id: 2,
    start: "08/12/2018",
    end: "05/06/2019",
    title: "Accent Coach",
    company: "Accent Advisor",
    country: "USA",
    state: "New York",
    description: "",
  }, 
  {
    id: 4,
    start: "05/15/2018",
    end: "08/31/2018",
    title: "Teacher	",
    company: "Natural English ",
    country: "Bolivia	",
    state: "Santa Cruz	",
    description: "",
  }, 
  {
    id: 3,
    start: "07/30/2019",
    end: "01/31/2019",
    title: "Teacher",
    company: "Dada Education Ltd.",
    country: "China",
    state: "Shanghai",
    description: "",
  }, 
  {
    id: 5,
    start: "05/01/2016",
    end: "05/01/2018",
    title: "Technical Support Agent",
    company: "BYU OIT",
    country: "USA",
    state: "Utah",
    description: "",
  }, 
  {
    id: 6,
    start: "10/01/2015",
    end: "12/31/2015",
    title: "Cleaner",
    company: "ServiceMaster by Webb",
    country: "USA",
    state: "Mississippi",
    description: "",
  }, 
  {
    id: 7,
    start: "05/14/2015",
    end: "06/01/2015",
    title: "Technician",
    company: "C-Spire Inc.",
    country: "USA",
    state: "Mississippi",
    description: "",
  }, 
  {
    id: 8,
    start: "08/07/2013",
    end: "05/12/2015",
    title: "Missionary",
    company: "Church of Jesus Christ of Latter Day Saints",
    country: "Ukraine",
    state: "Kyivska oblast",
    description: "",
  }, 
];

let portfolio = [
  {
    id: 2,
    title: "Music Room",
    description: "A website to showcase my wife's music classes",
    url: "music.daniellandry.me",
  },
  {
    id: 4,
    title: "Magic Dog Generator",
    description: "Implements two APIs to generate a random dog and assign it magical properties",
    url: "magicdog.daniellandry.me",
  },
  {
    id: 1,
    title: "BorisArte Photography",
    description: "A photography website built with HTML and CSS to showcase the photographer of my wedding",
    url: "lab1.daniellandry.me",
  },
  {
    id: 3,
    title: "Weather App",
    description: "Implements the OpenWeather API to get the weather from a given city and display it",
    url: "lab2.daniellandry.me",
  },
  {
    id: 5,
    title: "XKCD Browser",
    description: "Uses Vue to implement the XKCD API, allowing comments and ratings",
    url: "lab3.daniellandry.me",
  },
  {
    id: 6,
    title: "Mock Store",
    description: "Uses Vue to build a a store with a functional cart",
    url: "lab3b.daniellandry.me",
  },
];

