let work = [
  {
    id: 1,
    start: "02/08/2019",
    end: "12/12/2019",
    title: "Teacher",
    company: "Cambridge College, Bolivia",
    country: "Bolivia",
    state: "Santa Cruz",
    description: "Increase the English language skills of my students for international examination \nMake and implement annual, bimester, and weekly lesson plans  \nMaintain a nourishing learning environment in a classroom with 30+ students \nBuild relationships with parents and colleagues",
  }, 
  {
    id: 2,
    start: "08/12/2018",
    end: "05/06/2019",
    title: "Accent Coach",
    company: "Accent Advisor",
    country: "USA",
    state: "New York",
    description: "Corrected American accents with a detail-oriented approach \nBuilt relationships with my adult students through innovation of teaching methods",
  }, 
  {
    id: 4,
    start: "05/15/2018",
    end: "08/31/2018",
    title: "Teacher	",
    company: "Natural English ",
    country: "Bolivia	",
    state: "Santa Cruz	",
    description: "Explained English concepts to students at all ranges of fluency \nWorked with students aged 12-60+"
  }, 
  {
    id: 3,
    start: "07/30/2019",
    end: "01/31/2019",
    title: "Teacher",
    company: "Dada Education Ltd.",
    country: "China",
    state: "Shanghai",
    description: "Provided consistent quality in the instruction of students aged 4-18 \nCreated detailed daily feedback for parents to track their children’s progress",
  }, 
  {
    id: 5,
    start: "05/01/2016",
    end: "05/01/2018",
    title: "Technical Support Agent",
    company: "BYU OIT",
    country: "USA",
    state: "Utah",
    description: "Served customers in areas of LMS, Domain support, and others \nMonitored Network Devices \nTrained other agents",
  }, 
  {
    id: 6,
    start: "10/01/2015",
    end: "12/31/2015",
    title: "Cleaner",
    company: "ServiceMaster by Webb",
    country: "USA",
    state: "Mississippi",
    description: "Performed detailed cleaning and restoration of carpets and houses with fire-, and flood- damage",
  }, 
  {
    id: 7,
    start: "05/14/2015",
    end: "06/01/2015",
    title: "Technician",
    company: "C-Spire Inc.",
    country: "USA",
    state: "Mississippi",
    description: "Assisted in the installation of a ring of telecommunications radios \nDemonstrated highly precise work in challenging conditions",
  }, 
  {
    id: 8,
    start: "08/07/2013",
    end: "05/12/2015",
    title: "Missionary",
    company: "Church of Jesus Christ of Latter Day Saints",
    country: "Ukraine",
    state: "Kyivska oblast",
    description: "Acquired Russian skills in a challenging environment \nLead and instructed groups of 8 - 12 volunteers \nTaught English Classes to local residents ages 8 - 60+",
  }, 
];

export default work;
